/* eslint-disable */
// Generated by scripts/generate_api_client.py from FastAPI OpenAPI. Do not edit by hand.
export const OPENAPI_SCHEMA_HASH = "804982eefd64d0f45683fbef259c7734e6539f0e151a753b6491133b0b13564f";

export type AISettingsResponse = {
  "backend_only": boolean;
  "embedding_dimension": number;
  "embedding_model": string;
  "embeddings_enabled": boolean;
  "freshness_model": string;
  "gemini_configured": boolean;
  "generation_model": string;
  "lightweight_model": string;
  "live_smoke_enabled": boolean;
  "search_grounding_enabled": boolean;
  "search_grounding_model": string;
};

export type AnswerResponse = {
  "answer_text": string;
  "cache_status"?: string;
  "citations": Citation[];
  "confidence_label": string;
  "contradictions"?: Contradiction[];
  "evidence_chunk_ids": string[];
  "freshness_label": string;
  "live_grounding_used"?: boolean;
  "mode": string;
  "query_run_id": string;
  "refusal_reason": string | null;
  "route": string;
};

export type Body_upload_document_api_v1_workspaces__workspace_id__documents_post = {
  "file": string;
};

export type Citation = {
  "chunk_id": string;
  "evidence_text": string;
  "page_number": number | null;
  "section_heading": string | null;
  "source_filename": string;
};

export type CitedEvidenceTrace = {
  "chunk_id": string | null;
  "citation_label": string;
  "evidence_text": string;
  "source_kind": string;
};

export type Contradiction = {
  "chunk_ids": string[];
  "claim_key": string;
  "values": string[];
};

export type DependencyHealth = {
  "detail"?: string | null;
  "name": string;
  "status": string;
};

export type DependencyHealthResponse = {
  "services": DependencyHealth[];
};

export type DocumentResponse = {
  "chunk_count": number;
  "filename": string;
  "id": string;
  "mime_type": string;
  "status": string;
  "workspace_id": string;
};

export type DocumentStatusResponse = {
  "id": string;
  "status": string;
};

export type EvaluationRunResponse = {
  "run_id": string;
  "status": string;
  "summary": EvaluationSummary;
};

export type EvaluationSummary = {
  "cache_hit_rate": number;
  "case_count": number;
  "citation_validity_rate": number;
  "contradiction_correctness_rate": number;
  "latency_p50_ms": number;
  "latency_p95_ms": number;
  "refusal_correctness_rate": number;
  "retrieval_hit_rate": number;
  "secret_leak_count": number;
};

export type GeneratedAnswerTrace = {
  "answer_text": string;
  "confidence_label": string;
  "live_grounding_used": boolean;
  "refusal_reason": string | null;
};

export type HTTPValidationError = {
  "detail"?: ValidationError[];
};

export type HealthResponse = {
  "service": string;
  "status": string;
  "version": string;
};

export type LatencyMetricTrace = {
  "duration_ms": number;
  "metric_name": string;
};

export type QueryRequest = {
  "mode"?: "fast" | "verified";
  "query": string;
};

export type QueryRunTraceResponse = {
  "cache_status": string;
  "cited_evidence": CitedEvidenceTrace[];
  "generated_answer": GeneratedAnswerTrace | null;
  "id": string;
  "latency_metrics": LatencyMetricTrace[];
  "mode": string;
  "query_text": string;
  "retrieval_candidates": RetrievalCandidateTrace[];
  "route": string;
  "verification_result": VerificationResultTrace | null;
  "workspace_id": string;
};

export type RetrievalCandidateTrace = {
  "chunk_id": string;
  "page_number"?: number | null;
  "rank": number;
  "score": string;
  "section_heading"?: string | null;
  "source": string;
  "source_filename"?: string | null;
};

export type ValidationError = {
  "ctx"?: Record<string, unknown>;
  "input"?: unknown;
  "loc": (string | number)[];
  "msg": string;
  "type": string;
};

export type VerificationResultTrace = {
  "citation_valid": boolean;
  "contradiction_count": number;
  "details": Record<string, unknown>;
  "unsupported_claim_count": number;
};

export type WorkspaceCreateRequest = {
  "description"?: string | null;
  "name": string;
};

export type WorkspaceResponse = {
  "description": string | null;
  "id": string;
  "name": string;
};

export type FetchLike = typeof fetch;

export interface ProofPilotClientOptions {
  baseUrl?: string;
  fetch?: FetchLike;
}

export class ProofPilotApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly responseText: string,
  ) {
    super(message);
    this.name = "ProofPilotApiError";
  }
}

function normalizeBaseUrl(baseUrl: string): string {
  return baseUrl.replace(/\/$/, "");
}

function encodePathSegment(value: string): string {
  return encodeURIComponent(value);
}

async function requestJson<T>(
  fetcher: FetchLike,
  url: string,
  init: RequestInit,
): Promise<T> {
  const response = await fetcher(url, init);
  if (!response.ok) {
    const responseText = await response.text();
    throw new ProofPilotApiError(
      `ProofPilot API request failed with status ${response.status}.`,
      response.status,
      responseText,
    );
  }
  return (await response.json()) as T;
}

export function createProofPilotClient(options: ProofPilotClientOptions = {}) {
  const baseUrl = normalizeBaseUrl(options.baseUrl ?? "http://127.0.0.1:8000");
  const fetcher = options.fetch ?? fetch;

  return {
    getAISettings(): Promise<AISettingsResponse> {
      return requestJson(fetcher, `${baseUrl}/api/v1/settings/ai`, { method: "GET" });
    },

    getHealth(): Promise<HealthResponse> {
      return requestJson(fetcher, `${baseUrl}/api/v1/health`, { method: "GET" });
    },

    listWorkspaces(): Promise<WorkspaceResponse[]> {
      return requestJson(fetcher, `${baseUrl}/api/v1/workspaces`, { method: "GET" });
    },

    createWorkspace(payload: WorkspaceCreateRequest): Promise<WorkspaceResponse> {
      return requestJson(fetcher, `${baseUrl}/api/v1/workspaces`, {
        headers: { "Content-Type": "application/json" },
        method: "POST",
        body: JSON.stringify(payload),
      });
    },

    listDocuments(workspaceId: string): Promise<DocumentResponse[]> {
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/documents`,
        { method: "GET" },
      );
    },

    uploadDocument(workspaceId: string, file: File): Promise<DocumentResponse> {
      const body = new FormData();
      body.set("file", file);
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/documents`,
        { method: "POST", body },
      );
    },

    getDocumentStatus(documentId: string): Promise<DocumentStatusResponse> {
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/documents/${encodePathSegment(documentId)}/status`,
        { method: "GET" },
      );
    },

    queryWorkspace(workspaceId: string, payload: QueryRequest): Promise<AnswerResponse> {
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/query`,
        {
          headers: { "Content-Type": "application/json" },
          method: "POST",
          body: JSON.stringify(payload),
        },
      );
    },

    getQueryRun(queryRunId: string): Promise<QueryRunTraceResponse> {
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/query-runs/${encodePathSegment(queryRunId)}`,
        { method: "GET" },
      );
    },

    runEvaluation(): Promise<EvaluationRunResponse> {
      return requestJson(fetcher, `${baseUrl}/api/v1/evaluations/run`, { method: "POST" });
    },

    getEvaluationRun(runId: string): Promise<EvaluationRunResponse> {
      return requestJson(
        fetcher,
        `${baseUrl}/api/v1/evaluations/runs/${encodePathSegment(runId)}`,
        { method: "GET" },
      );
    },

    getMetricsSummary(): Promise<EvaluationSummary> {
      return requestJson(fetcher, `${baseUrl}/api/v1/metrics/summary`, { method: "GET" });
    },
  };
}
