from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

OUTPUT_PATH = Path(__file__).resolve().parents[1] / "packages" / "generated-api-client" / "src" / "index.ts"

sys.path.insert(0, str(Path.cwd()))

from app.main import app  # noqa: E402


def schema_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema_ref_name(str(schema["$ref"]))

    if "anyOf" in schema:
        return " | ".join(ts_type(option) for option in schema["anyOf"])

    schema_type = schema.get("type")
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        if schema.get("format") == "binary":
            return "File"
        enum_values = schema.get("enum")
        if enum_values:
            return " | ".join(json.dumps(value) for value in enum_values)
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        item_type = ts_type(schema.get("items", {}))
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema:
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            return "Record<string, unknown>"
        lines = ["{"]
        for name, property_schema in sorted(properties.items()):
            optional = "" if name in required else "?"
            lines.append(f"  {json.dumps(name)}{optional}: {ts_type(property_schema)};")
        lines.append("}")
        return "\n".join(lines)
    return "unknown"


def emit_schema_aliases(openapi: dict[str, Any]) -> list[str]:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines: list[str] = []
    for name, schema in sorted(schemas.items()):
        lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    return lines


def stable_openapi_hash(openapi: dict[str, Any]) -> str:
    payload = json.dumps(openapi, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def generated_source(openapi: dict[str, Any]) -> str:
    schema_lines = emit_schema_aliases(openapi)
    openapi_hash = stable_openapi_hash(openapi)
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_api_client.py from FastAPI OpenAPI. Do not edit by hand.",
        f'export const OPENAPI_SCHEMA_HASH = "{openapi_hash}";',
        "",
        *schema_lines,
        "export type FetchLike = typeof fetch;",
        "",
        "export interface ProofPilotClientOptions {",
        "  baseUrl?: string;",
        "  fetch?: FetchLike;",
        "}",
        "",
        "export class ProofPilotApiError extends Error {",
        "  constructor(",
        "    message: string,",
        "    public readonly status: number,",
        "    public readonly responseText: string,",
        "  ) {",
        "    super(message);",
        '    this.name = "ProofPilotApiError";',
        "  }",
        "}",
        "",
        "function normalizeBaseUrl(baseUrl: string): string {",
        '  return baseUrl.replace(/\\/$/, "");',
        "}",
        "",
        "function encodePathSegment(value: string): string {",
        "  return encodeURIComponent(value);",
        "}",
        "",
        "async function requestJson<T>(",
        "  fetcher: FetchLike,",
        "  url: string,",
        "  init: RequestInit,",
        "): Promise<T> {",
        "  const response = await fetcher(url, init);",
        "  if (!response.ok) {",
        "    const responseText = await response.text();",
        "    throw new ProofPilotApiError(",
        '      `ProofPilot API request failed with status ${response.status}.`,',
        "      response.status,",
        "      responseText,",
        "    );",
        "  }",
        "  return (await response.json()) as T;",
        "}",
        "",
        "export function createProofPilotClient(options: ProofPilotClientOptions = {}) {",
        '  const baseUrl = normalizeBaseUrl(options.baseUrl ?? "http://localhost:8000");',
        "  const fetcher = options.fetch ?? fetch;",
        "",
        "  return {",
        "    getAISettings(): Promise<AISettingsResponse> {",
        '      return requestJson(fetcher, `${baseUrl}/api/v1/settings/ai`, { method: "GET" });',
        "    },",
        "",
        "    getHealth(): Promise<HealthResponse> {",
        '      return requestJson(fetcher, `${baseUrl}/api/v1/health`, { method: "GET" });',
        "    },",
        "",
        "    listWorkspaces(): Promise<WorkspaceResponse[]> {",
        '      return requestJson(fetcher, `${baseUrl}/api/v1/workspaces`, { method: "GET" });',
        "    },",
        "",
        "    createWorkspace(payload: WorkspaceCreateRequest): Promise<WorkspaceResponse> {",
        "      return requestJson(fetcher, `${baseUrl}/api/v1/workspaces`, {",
        '        headers: { "Content-Type": "application/json" },',
        '        method: "POST",',
        "        body: JSON.stringify(payload),",
        "      });",
        "    },",
        "",
        "    listDocuments(workspaceId: string): Promise<DocumentResponse[]> {",
        "      return requestJson(",
        "        fetcher,",
        "        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/documents`,",
        '        { method: "GET" },',
        "      );",
        "    },",
        "",
        "    uploadDocument(workspaceId: string, file: File): Promise<DocumentResponse> {",
        "      const body = new FormData();",
        '      body.set("file", file);',
        "      return requestJson(",
        "        fetcher,",
        "        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/documents`,",
        '        { method: "POST", body },',
        "      );",
        "    },",
        "",
        "    getDocumentStatus(documentId: string): Promise<DocumentStatusResponse> {",
        "      return requestJson(",
        "        fetcher,",
        "        `${baseUrl}/api/v1/documents/${encodePathSegment(documentId)}/status`,",
        '        { method: "GET" },',
        "      );",
        "    },",
        "",
        "    queryWorkspace(workspaceId: string, payload: QueryRequest): Promise<AnswerResponse> {",
        "      return requestJson(",
        "        fetcher,",
        "        `${baseUrl}/api/v1/workspaces/${encodePathSegment(workspaceId)}/query`,",
        "        {",
        '          headers: { "Content-Type": "application/json" },',
        '          method: "POST",',
        "          body: JSON.stringify(payload),",
        "        },",
        "      );",
        "    },",
        "",
        "    runEvaluation(): Promise<EvaluationRunResponse> {",
        '      return requestJson(fetcher, `${baseUrl}/api/v1/evaluations/run`, { method: "POST" });',
        "    },",
        "",
        "    getEvaluationRun(runId: string): Promise<EvaluationRunResponse> {",
        "      return requestJson(",
        "        fetcher,",
        "        `${baseUrl}/api/v1/evaluations/runs/${encodePathSegment(runId)}`,",
        '        { method: "GET" },',
        "      );",
        "    },",
        "",
        "    getMetricsSummary(): Promise<EvaluationSummary> {",
        '      return requestJson(fetcher, `${baseUrl}/api/v1/metrics/summary`, { method: "GET" });',
        "    },",
        "  };",
        "}",
        "",
    ]
    source = "\n".join(lines)
    return re.sub(r"\n{3,}", "\n\n", source)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated client is stale")
    args = parser.parse_args()

    source = generated_source(app.openapi())

    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if existing != source:
            print(f"{OUTPUT_PATH} is stale. Run scripts/generate_api_client.py.", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(source, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
